### PR TITLE
Fix 249: Shapeless-powered Router

### PR DESCRIPTION
**Pull request by vkostyukov**
This work is in progress. I haven't deprecated the `/` type yet, but planning to do so. I was trying to follow the style/ideas @travisbrown used for request readers.

I added just one test for now.

### CODE REVIEW

**Comment by travisbrown** [comment]
What do you think about keeping the `/` syntax? We could still use `HList` behind the scenes.

**Comment by vkostyukov** [comment]
I was thinking about keeping the `/` API unchanged: I'm pretty sure some users rely on the `/` composite type and use pattern-patching over it. As far as I remember, @ImLiar was doing something like this with custom implicit conversions over the `/` type.

Although, it seems to me that it's quite possible to migrate from `/` to `::`. And the changes are quite mechanical. So, maybe we should just break the current API. My only wish is to introduce the `::` method as an alternative: for consistency.

**Comment by vkostyukov** [comment]
Rebased against master but haven't touched the API yet.

**Comment by vkostyukov** [comment]
I tried to reuse the `/` method name: it seems to be painfull. I would much prefer a name that ends with colon to simplify the implementation. So I would go with `::` for now.

**Comment by ImLiar** [comment]
I was on vacation and skipped a lot with new router API. 
Whats the pain with `/` method name? Is it possible to make at least alias method `/` -> `::`?

**Comment by vkostyukov** [comment]
I've rebased it against master.

@ImLiar answering your question. The reason for this is a special treatment of operators like "::" (ends with a colon). Using the right-associative operator `::` allows us build HList routers pretty easy since we're basically doing in the same manner we build lists: from right to left (starting with `Nil` and pretending heads one-by-one).

With left-associative operator `/` we would need to _append_ new element to HList. This is the one problem. The other problem is how to tell the difference between `Router[String]` and `Router[HList]` in terms of `def /[A](that: Router[A])`. This information is not available at runtime, but it's available at compile time, so we had `implicit class RouterOps[L <: HList](r: Router[L])`.

**Comment by ImLiar** [comment]
Oh, I completely forgot about associativity in scalac. Well, from this point it sounds reasonable.

**Comment by travisbrown** [comment]
It's possible to build up hlists with a left-associative operator in a way that's not too terrible (see [this](https://gist.github.com/travisbrown/826aea169b149931739d) for a similar coproduct example).

I'd personally prefer `/`, in part to distinguish it from the `::` for request readers, since what's happening here is very different—we're consuming tokens off a stack, not composing independent reading operations. I'll try to make a bit of time to look at this this afternoon, but might not get to it until tomorrow.

**Comment by vkostyukov** [comment]
Closed in favour of #306.

**Pull request closed without merging**
