### PR TITLE
Capture Traces

### PR DESCRIPTION
**Pull request by vkostyukov**
As discussed in #959. Here is how it works (from the user perspective).

```scala
scala> import io.finch._, io.finch.syntax._
import io.finch._
import io.finch.syntax._

scala> val foo = get("foo" :: path[String]) { s: String => Ok(s) }
foo: io.finch.Endpoint[String] = GET /foo :: :string

scala> import com.twitter.finagle.http.Request
import com.twitter.finagle.http.Request

scala> val s = foo.toServiceAs[Text.Plain]
s: com.twitter.finagle.Service[com.twitter.finagle.http.Request,com.twitter.finagle.http.Response] = io.finch.ToService$$anon$4$$anon$2

scala> Trace.capture { s(Request("/foo/bar")).map(_ => Trace.captured) }
res0: com.twitter.util.Future[io.finch.Trace] = Promise@406161512(state=Done(Return(/foo/:string)))
```

### CODE REVIEW

**Comment by sergeykolbasov** [comment]
👍 

Let's merge it and release. We have instant cases that will be solved using it

**Comment by rpless** [comment]
LGTM. I'm 👍 to getting this into the next release too.

**Comment by vkostyukov** [comment]
@sergeykolbasov I'm debating myself on whether there is a need for a bootstrap option. Having both (bootstrap option and `Trace.capture`) seems to be redundant for me. I will run some benchmarks to see how expensive that local lookup (based on what we've seen in FInagle it could be quite expensive).

**Comment by vkostyukov** [comment]
Nothing stands out of the benchmark runs (just a drop in the ocean). Also, it's pretty volatile so somehow the new code is faster than old. Again, I think it's just noise, nothing to be concerned about.

```
BEFORE:

[info] Benchmark                                                   Mode  Cnt      Score      Error   Units
[info] TextBootstrapBenchmark.foos                                thrpt   10  68824.182 ± 2454.004   ops/s
[info] TextBootstrapBenchmark.foos:·gc.alloc.rate.norm            thrpt   10  47888.021 ±    0.008    B/op

AFTER:

[info] Benchmark                                                   Mode  Cnt      Score      Error   Units
[info] TextBootstrapBenchmark.foos                                thrpt   10  70165.207 ± 2442.619   ops/s
[info] TextBootstrapBenchmark.foos:·gc.alloc.rate.norm            thrpt   10  47904.100 ±    0.308    B/op
```

**Comment by sergeykolbasov** [comment]
@vkostyukov ok, that's nice. Have no questions

**Pull request merged**
