### PR TITLE
Kill micro

### PR DESCRIPTION
**Pull request by vkostyukov**
The `micro` package was marked "experimental" so I belive we have rights to do that.

### CODE REVIEW

**Comment by travisbrown** [comment]
Sounds reasonable to me, but is there a strong reason not to let it live out the deprecation cycle?

**Comment by vkostyukov** [comment]
Makes sense. Let's keep this open until 0.7.0.

**Comment by travisbrown** [comment]
I'd be happy to pull the trigger on this now that 0.7.0 is out.

**Comment by vkostyukov** [comment]
I'm about to submit release notes (tag will be attached to HEAD). After that we can start deleting stuff!

**Comment by vkostyukov** [comment]
Let's kill it!

**Pull request merged**
