### PR TITLE
Prepare a release 0.25

### PR DESCRIPTION
**Pull request by vkostyukov**
- Drops iteratee-twitter dependency
- Bumps Finagle to 18.10
- Triggers a release.

### CODE REVIEW

**Comment by arron-green** [comment]
fixed in #1008

**Comment by vkostyukov** [comment]
This almost worked @arron-green, here is the last error:

```
[info] Reapplying settings...
[info] Set current project to finch (in build file:/home/travis/build/finagle/finch/)
[info] Setting version to '0.25.1-SNAPSHOT'.
[info] Reapplying settings...
[info] Set current project to finch (in build file:/home/travis/build/finagle/finch/)
[info] [master 7a8569e] Setting version to 0.25.1-SNAPSHOT
[info]  1 file changed, 1 insertion(+), 1 deletion(-)
[error] java.lang.RuntimeException: Invalid programmatic input:
[error] Not a valid command: sonatypeReleaseAll
[error] Not a valid project ID: sonatypeReleaseAll
[error] Expected ':'
[error] Not a valid key: sonatypeReleaseAll
[error] sonatypeReleaseAll
[error]                   ^
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbtrelease.ReleasePlugin$autoImport$.$anonfun$releaseStepCommand$2(ReleasePlugin.scala:94)
[error] 0m	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:176)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$9(ReleasePlugin.scala:194)
[error] 	at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:200)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:154)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:137)
[error] [0m	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:137)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:137)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:130)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:108)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:102)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:58)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:43)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)m
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Invalid programmatic input:
[error] Not a valid command: sonatypeReleaseAll
[error] Not a valid project ID: sonatypeReleaseAll
[error] Expected ':'
[error] Not a valid key: sonatypeReleaseAll
[error] sonatypeReleaseAll
[error]                   ^
[error] Use 'last' for the full log.
```

Sounds like we're missing a plugin or something?

**Comment by vkostyukov** [comment]
I'm adding `addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.0")` and trying again.

**Comment by vkostyukov** [comment]
It worked! The `finchx` release has hit the MC. I'm working on a regular release now.

**Comment by arron-green** [comment]
@vkostyukov this is great news!

**Pull request merged**
