### PR TITLE
add Qubit to users

### PR DESCRIPTION
**Pull request by jibs**
Thanks for an awesome project :)

### CODE REVIEW

**Comment by vkostyukov** [comment]
Hi @jibs! 

This is awesome! I'm very glad Finch is used to build such cool things like Qubit!

Do you mind to share a bit of detail (since which version do you use Finch, what modules do you use etc.) so I and other Finch developers could understand the priorities of our adopters?

**Comment by vkostyukov** [comment]
I've merged it. Thanks @jibs!

**Comment by jibs** [comment]
Sorry for the delay :)

Sure - we're using a bunch of different versions - vast majority is 0.6.0 at the moment. Primarily finch is augmenting a lot of the internal routing stuff we wrote at Qubit (we've been using finagle for a while so there is a lot of this code). There have been some tiny contributions back by us but we hope to make this more substantial as finch gets more traction here.

Thanks again!

**Comment by vkostyukov** [comment]
Thanks @jibs! This is grreat!

**Pull request merged**
