### PR TITLE
Remove ToTwitterFuture trait and replace it with cats.arrow.FunctionK

### PR DESCRIPTION
**Pull request by sergeykolbasov**
cats library provides sufficient for our need abstraction out of the box to map `F[A] => G[A]`.
Remove ToTwitterFuture as obsolete and replace it with type alias for the sake of compatibility

### CODE REVIEW

**Comment by vkostyukov** [comment]
How does the instance for Scala Future work/look? I don't see changes for it.

**Comment by sergeykolbasov** [comment]
@vkostyukov What's the difference? Of what I see that's going to be the same anonymous instance of `FunctionK`. Taking in account that it's `val` in the end, there is almost no additional price to pay.

**Comment by vkostyukov** [comment]
I'd assume we won't actually need `ToTwitterFuture` should go with cats-effect? Maybe it's not really worth improving on them then?

**Comment by sergeykolbasov** [comment]
Still need it once we convert `F[_]` to `Future` in `ToService`

**Pull request closed without merging**
