### PR TITLE
Update finagle to 17.10.0

### PR DESCRIPTION
**Pull request by ImLiar**
New version was released few days ago

Also update catbird & iteratee

### CODE REVIEW

**Comment by travisbrown** [comment]
If the only thing blocking the upgrade to Cats 1.0.0-RC1 is circe-jackson I can try to get that published today.

**Comment by ImLiar** [comment]
@travisbrown it would be awesome! Thanks

**Comment by vkostyukov** [comment]
I think we also need circe-streaming (which is being extracted from Circe) to do a Cats upgrade.

**Comment by vkostyukov** [comment]
@ImLiar Looks like we need to depend on logging explicitly (based on https://travis-ci.org/finagle/finch/jobs/297979347). I'd just replace `log()` with `println` for now.

**Comment by travisbrown** [comment]
@vkostyukov You're right, sorry—I'll try to sort out https://github.com/travisbrown/iteratee/pull/218 tonight. In the meantime circe-jackson's ready.

**Comment by ImLiar** [comment]
@vkostyukov 

Yep, I'm on it with fixing a logger

**Comment by vkostyukov** [comment]
Thanks @ImLiar! Merging this in.

**Comment by ImLiar** [comment]
@vkostyukov there are still some warning (potential binary incompatibilities) because `circe-streaming` wasn't releassed yet. Waiting for iteratee tests fix

**Comment by vkostyukov** [comment]
Yeah. Looks like we also need to bump discipline's version.

**Pull request merged**
