### PR TITLE
Aggregate refined

### PR DESCRIPTION
**Pull request by rider-yi**
I just noticed that the new `finch-refined` module wasn't being published.

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.github.finagle#finch-refined_2.12;0.22.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

### CODE REVIEW

**Comment by vkostyukov** [comment]
Oh that's a good catch. Thanks @rider-yi!

CI fails with the following error on 2.11:

```
/home/travis/build/finagle/finch/refined/src/main/scala/io/finch/refined/package.scala:12:88: value toOption is not a member of Either[String,F[A,B]]
[error]   ): DecodePath[F[A, B]] = DecodePath.instance(s => ad(s).flatMap(p => rt.refine[B](p).toOption))
```

Do you have any idea why? I restarted the job just in case.

**Comment by rpless** [comment]
@vkostyukov I think its Scala 2.11 v 2.12 related. Pretty sure in Scala 2.11 `Either` doesn't have `toOption` in Scala 2.11. Cats has an implicit syntax for it, we'll either have to use that or manually fold the `Either` here.

**Comment by vkostyukov** [comment]
I see. Sounds like we never compiled it for 2.11 hence never saw an error. Importing Cats' syntax works for me, fwiw. @rider-yi any chance you want to fix this as part of this PR?

**Comment by rider-yi** [comment]
I just fixed the error with [RightProjection](https://www.scala-lang.org/api/2.12.x/scala/util/Either$$RightProjection.html). It seems that importing Cats's syntax causes unused warning:
```
[warn] /Users/yu_ishikawa/finch/refined/src/main/scala/io/finch/refined/package.scala:3:27: Unused import
[warn] import cats.syntax.either._
[warn]                           ^
```

**Comment by vkostyukov** [comment]
Changes look good to me! Thanks again, @rider-yi!

**Comment by vkostyukov** [comment]
Cherry-picked this into `arrows`: 3ffa8808e7d12fea4efc4f1b49582d20c42794fb and bd92d61a7bc5aa22b6d7f2463b3dd4411bca0c4a.

**Pull request merged**
