### PR TITLE
Greedy routers

### PR DESCRIPTION
**Pull request by vkostyukov**
Realised that I missed an important part in routers. In case of two similar routes like `/users/:id` and `/users` it wasn't really clear how to chose the right router in `orElse` combinator. The previous implementation was always taking the first succeed router, which is wrong in the following case:

```scala
val r = (Get / "users" /> GetAllUsers) | (Get / "users" / int /> GetUser)
r("/users/10") // returns GetAllUsers
``` 

This PR introduces a simple and clean approach: always take a router that eats more route tokens (sort of greedy router). I also made a routing more strict - we don't route the requests whose path wasn't fully matched.

### CODE REVIEW

**Comment by vkostyukov** [comment]
If somebody knows a better way to find a minimum of values inside two options let me know.

**Comment by vkostyukov** [comment]
Simplified it. I think it's ready to be merged.

**Comment by vkostyukov** [comment]
I'm going to merge it tomorrow. Let me know if you have any concerns about this. //cc @rpless, @rodrigopr, @BenWhitehead, @jenshalm

**Comment by BenWhitehead** [comment]
I think this is a great convenience rather than the user having to do the ordering manually.

**Comment by rpless** [comment]
:+1: although we do need to document it.

**Comment by vkostyukov** [comment]
Sure. I was planing to add a section about route combinators.

**Pull request merged**
