### PR TITLE
Cat's Xor Encoder

### PR DESCRIPTION
**Pull request by ImLiar**
Simple encoder for #504

Still there is a question about dynamic `contentType`.

### CODE REVIEW

**Comment by vkostyukov** [comment]
Thanks @ImLiar!

I'm starting to think that it might be a good idea to decouple content-type from `EncodeResponse` and have a separate type-class for this. Looking at @travisbrown's #329, we might want to represent it as a type-level string (a singleton type). Something like:

```scala
trait ContentType[A] {
  type C <: String
}

object ContentType {
  type Aux[A, C0 <: String] = ContentType[A] { type C = C0}

  def instance[A, C0 <: String](implicit w: shapeless.Witness.Aux[C0]): ContentType.Aux[A, C0] =
    new ContentType[A, C0] {
      type C = C0
      override def toString: String = w.value
    }
}

implicit val ctUser: ContentType[User] = ContentType.instance[User, shapeless.Witness.`"text/plain"`.T]
```

**Comment by ImLiar** [comment]
@vkostyukov 

I'm missing a point of. What about value rather than type based cases of `Content-Type` application? 
I.e. `String` could be `plain/text` or `application/octet-stream`.

**Comment by travisbrown** [comment]
@ImLiar Type class instances are resolved statically, so that process can't consult a value-level string. If you want e.g. different modules to provide encoding logic for JSON and XML content types, it takes a lot more coordination to provide a single encoder that knows about both of those operations and dispatches to the appropriate one at runtime based on a value-level content type string.

**Comment by vkostyukov** [comment]
Thanks @travisbrown!

That's a known problem in Finch: it's hard to distinct two (or more) different content types returned from Finch endpoints. Generally, once you've imported `io.finch.circe._` you've made everything a JSON. Ideally we want to be able to tell for a given endpoint/output what encoder to use (depending on a content-type), which is why we need it life content-type into an actual type so it could affect the implicit encoder being picked up a compiler.

Indeed, encoders for `cats.Xor` and type-level content-type are two different problems that needs to be solved, but I think they overlap - it's worth trying to approach them together.

**Comment by vkostyukov** [comment]
I'm also totally fine to handle content-type as a type in a separate PR (maybe it's even better).

**Comment by vkostyukov** [comment]
Okay, thinking about this more, #329 is exactly what we need right now given that we now have proper tooling (`Endpoint.withConentType`, `Output.withConentType`) to make it available for users. @travisbrown are you interested by any chance to pick it up, rebase and update to the current Finch's state. I'm totally happy to do that myself, if you're swamped with other tasks at this moment.

**Comment by ImLiar** [comment]
@vkostyukov @travisbrown 

AFAIK typed `CT` already in master. May be I should update this PR or there are some pitfalls?

**Comment by vkostyukov** [comment]
Thanks for the follow up, @ImLiar!

Yeah, I guess, we can try doing that. Let's think of something like using matching content-type for left and right cases.

```scala
implicit def encodeXor[A, B, CT <: String](implicit 
  ea: Encode.Aux[A, CT], 
  eb: Encode.Aux[B, CT]): Encode.Aux[Xor[A, B], CT]
```

**Comment by ImLiar** [comment]
Are you sure about single `Content-Type`?

**Comment by ImLiar** [comment]
:checkered_flag:

**Comment by vkostyukov** [comment]
I guess so. Given that which content-type to use is determined on the vey last step (`toService`), endpoints are content-type-less so I don't think we need to support two different content-types for `Xor`. It should be decided at a different layer, how to encode a value.

**Comment by vkostyukov** [comment]
@ImLiar I'd probably vote for not providing a separate example for `Xor`. Perhaps, we could use it in some of the existing examples or even just mention in docs. Let's just remove it for now and figure this out later.

**Comment by ImLiar** [comment]
@vkostyukov I suppose we could move it to cookbook. Just to make sure

**Comment by vkostyukov** [comment]
Yeah, good idea! Let's add cookbook recipe!

**Comment by vkostyukov** [comment]
@ImLiar Mind rebasing this? Feel free to keep just an implementation - I can add docs later in the upcoming commits.

**Comment by ImLiar** [comment]
@vkostyukov Ok. Done

**Comment by vkostyukov** [comment]
Thanks @ImLiar!

**Pull request merged**
