### PR TITLE
Fixed the broken codecov shield

### PR DESCRIPTION
**Pull request by rpless**
Also a good test to see if codecov.io PR commenting is on. We need to opt-in to that feature, so if we don't get a comment, it might not be on.

### CODE REVIEW

**Comment by vkostyukov** [comment]
Cool! Why aren't we getting coverage reports already?

**Comment by rpless** [comment]
@vkostyukov Unlike Coveralls, you need to opt-in to PR comments (they're also highly configurable). On the project page (https://codecov.io/github/finagle/finch) there is a features dropdown all the way to the right. Click on the Pull Request Comments Feature and turn it on.

**Comment by vkostyukov** [comment]
Yeah. I've already checked it. Thanks, Ryan!

**Comment by rpless** [comment]
Interesting. I took a look at the one here (https://github.com/rpless/finch/pull/2). Looks like there's ~5 minutes between Travis finishing and comment being posted (obviously not the most scientific way to determine this, but shows there might be a bit of a delay). So we should start seeing them.

**Pull request merged**
