### PR TITLE
Add Jackson serialiser for Circe

### PR DESCRIPTION
**Pull request by mtnajim**
Provide support for Jackson serialiser from Circe to improve performance

### CODE REVIEW

**Comment by vkostyukov** [comment]
The build is broken bue to binary incompatibility in the Circe's and Finch's Jackson versions. Let me update Jackson version to make this green.

**Comment by travisbrown** [comment]
We could probably also downgrade on the circe side if that would make things easier.

**Comment by vkostyukov** [comment]
@travisbrown No wories, I think it makes sense to upgrage Finch to the latest Jackson version anyway. So let's do it now.

**Comment by vkostyukov** [comment]
I rebased this PR here: #492. Thanks again @mtnajim! I will merge once once it's green.

**Pull request closed without merging**
