### PR TITLE
Introduce RouterInput

### PR DESCRIPTION
**Pull request by vkostyukov**
This PR is a first step towards #232. In order to compose routers with request readers, we have to carry the `HttpRequest` within `Route`. This PR introduces `RouterInput` for that purpose. I also went ahead and refactored the compositors around method matches. The previous approach felt weird and didn't really fitted well into the combinators API. The new approach is based on simple functions (compositors) `get`, `post`, etc that takes a router and returns a new router that also matches the method.

This still requires some polish but it's ready for review.

### CODE REVIEW

**Comment by rpless** [comment]
:+1: I like the direction its going. It seems like it shouldn't be too difficult to extend this to include parameters/headers/etc. It also appears like we can easily traverse the route and inspect it programmatically.

**Comment by vkostyukov** [comment]
Thanks @rpless!

@travisbrown do you mind take a look?

**Comment by vkostyukov** [comment]
This needs to be rebased though.

**Comment by vkostyukov** [comment]
Rebased it. Would appreciate any feedback on this. /cc @travisbrown @penland365.

**Comment by travisbrown** [comment]
@vkostyukov Any change that makes more illegal states unrepresentable sounds good to me, and I like this implementation.

**Comment by vkostyukov** [comment]
Okay.  I decided to not deprecate method matchers (a la `Get`, `Post`, etc) for now. So we can merge this in once it's green.

**Pull request merged**
