### PR TITLE
Update Finagle to 6.36.0 and use new catbird release

### PR DESCRIPTION
**Pull request by travisbrown**
I'm not sure when we're planning for this update to happen, but I just published a [new catbird.io release](https://github.com/travisbrown/catbird/releases/tag/v0.6.0) that depends on Finagle 6.36.0.

### CODE REVIEW

**Comment by crispywalrus** [comment]
:+1: on pushing this into the 0.11 milestone

**Comment by vkostyukov** [comment]
Thanks, Travis! I was hoping to get 0.11 released for both 2.10 and 2.11. That means staying on 6.35 for a while. Although, I'm not 100% sold on this idea yet so maybe we can (should?) drop 2.10 support in 0.11.

**Comment by tomjadams** [comment]
FWIW I'm +1 on 2.11 only.

**Comment by dave-bemiller-ck** [comment]
+1 on 2.11 only here, too

**Comment by KadekM** [comment]
+1 on 2.11 only here

**Comment by travisbrown** [comment]
Superseded by #629.

**Pull request closed without merging**
