### PR TITLE
Update Scala 2.11 and other dependencies and plugins

### PR DESCRIPTION
**Pull request by travisbrown**
This doesn't include the Finagle update, since I didn't know whether we wanted to publish a new finagle-oauth2 first, but it updates everything else.

### CODE REVIEW

**Comment by vkostyukov** [comment]
Thanks a lot @travisbrown!

I think I'm going to use :heart: for every single Finch PR now!

**Comment by travisbrown** [comment]
Ugh, looks like the 1.3.3-to-1.3.5 update for sbt-scoverage is having the same effect as I saw [here](https://github.com/travisbrown/iteratee/issues/54). Let me take a closer look…

**Comment by travisbrown** [comment]
Okay, this PR no longer drops coverage to 0.0%!

**Comment by vkostyukov** [comment]
Thanks again! Merging this.

**Pull request merged**
