### PR TITLE
Ench #186: Default value for optional readers

### PR DESCRIPTION
**Pull request by ImLiar**
Simple implementation based on scala `Option` methods

### CODE REVIEW

**Comment by ImLiar** [comment]
Oh wow... Some bugs with coveralls

**Comment by vkostyukov** [comment]
Yep. Sometimes this happens. Still don't have time to dig in and find out why this happens /cc: @rpless.

The PR looks cool! Thanks a lot!

**Comment by vkostyukov** [comment]
BTW, @ImLiar do you use Finch in production? If so do you mind adding you company into the adopters lists?

**Comment by ImLiar** [comment]
@vkostyukov we are still at very early development stage, but yeah, I remember about adopters list :smile:

**Pull request merged**
