### PR TITLE
Use Jawn Parser for Argonaut

### PR DESCRIPTION
**Pull request by rpless**
I just realized that the fix for jawn was pushed a long time ago and that the fix for #287 has just been sitting here. I'm not sure if we still want to make this change, but I'll leave it here for experimentation.

### CODE REVIEW

**Comment by vkostyukov** [comment]
Thanks @rpless! Mind running some benchmarks we have to understand how it impacts the default performance?

**Comment by rpless** [comment]
Benchmarks:

With Jawn: https://gist.github.com/rpless/8403fec7aa0c497ece1c
```
[info] Benchmark                         Mode  Cnt    Score    Error  Units
[info] ArgonautBenchmark.deleteAllUsers  avgt   20    0.336 ±  0.012  ms/op
[info] ArgonautBenchmark.getAllUsers     avgt   20   24.891 ±  5.845  ms/op
[info] ArgonautBenchmark.getUsers        avgt   20  224.991 ±  8.089  ms/op
[info] ArgonautBenchmark.createUsers       ss   20  183.914 ±  7.255  ms/op
[info] ArgonautBenchmark.updateUsers       ss   20  270.715 ± 20.802  ms/op
```

Currently: https://gist.github.com/rpless/8a138111d8895f17cdba
```
[info] Benchmark                         Mode  Cnt    Score    Error  Units
[info] ArgonautBenchmark.deleteAllUsers  avgt   20    0.338 ±  0.014  ms/op
[info] ArgonautBenchmark.getAllUsers     avgt   20   24.911 ±  5.868  ms/op
[info] ArgonautBenchmark.getUsers        avgt   20  221.841 ± 10.489  ms/op
[info] ArgonautBenchmark.createUsers       ss   20  176.838 ±  9.056  ms/op
[info] ArgonautBenchmark.updateUsers       ss   20  258.012 ± 15.953  ms/op
```

**Comment by vkostyukov** [comment]
@rpless Mind rebasing this? I'm thinking about merging this.

**Comment by vkostyukov** [comment]
Thanks @rpless! I'm merging this!

**Pull request merged**
