### PR TITLE
Add Spright to adopters list

### PR DESCRIPTION
**Pull request by keeth**
Hello, we use finch in production, in several backend microservices - we love it.  We just launched a couple weeks ago.  Feel free to add us to your adopters list.  Thanks!!

### CODE REVIEW

**Comment by vkostyukov** [comment]
This is awesome @keeth! 

Can you share a bit of details in wich configuration you use Finch (version, modules, etc)? This would be very helpful for me and other contributors in order to understand our priorities.

**Comment by keeth** [comment]
Hi @vkostyukov, sure we are on 0.5.0 and use the core and argonaut modules.  Finch was the deciding factor for using Finagle at all - really like the routing syntax and JSON handling.

**Comment by vkostyukov** [comment]
Nice! Thanks!

There is a nice integration library between Argonaut and Shapeless: https://github.com/alexarchambault/argonaut-shapeless. It will automatically derive any instances of `EncodeJson`/`DecodeJson` for any class. The following code illustrates this magic. 

```scala
import argonaut._, Argonaut._, Shapeless._
import io.finch.argonaut._
import io.finch.response._
import io.finch.request._

case class User(id: Int, name: String)

val rep = Ok(User(1, "Bob"))
val req = body.as[User]
```

Again, thanks a lot for this!

**Comment by keeth** [comment]
Cool, I have heard good things about Shapeless but have not tried it yet, thanks for the tip!

**Comment by travisbrown** [comment]
@keeth We'd love to have a PR adding Spright to [the Finagle adopters list](https://github.com/twitter/finagle/blob/develop/ADOPTERS.md) as well!

**Pull request merged**
