### PR TITLE
moves decrypt within push branch

### PR DESCRIPTION
**Pull request by arron-green**
finishes work left from #1461 

only decrypt release files on `push`

### CODE REVIEW

**Review by joroKr21 — APPROVED** [review]

**Comment by rpless** [comment]
Ok I've merged mine. Once this build passes we can merge this too and then attempt a deploy.

**Comment by rpless** [comment]
Ok. We should be good to release now. @tpetillot @joroKr21 do one of you want to attempt another release?

**Comment by rpless** [comment]
Uh well hold on. the master branch seems to be broken even though this passed.

**Comment by rpless** [comment]
There appears to be a problem with the content of the credentials.sbt file. I'm investigating.

**Comment by joroKr21** [comment]
Sure I can push a commit

**Comment by joroKr21** [comment]
@rpless it didn't work: https://github.com/finagle/finch/runs/5887648393?check_suite_focus=true

**Comment by rpless** [comment]
Hrm, not sure why it's getting that error. I can do some digging later today.

**Comment by vkostyukov** [comment]
This the error extracted from logs:

```

[info] git@github.com: Permission denied (publickey).
[info] fatal: Could not read from remote repository.
[info] Please make sure you have the correct access rights
[info] and the repository exists.
```

**Comment by vkostyukov** [comment]
FYI: I was able to log in to sonatype using the credentials in the encrypted credentials.sbt.

**Comment by vkostyukov** [comment]
Ah ok, maybe it's Github? Not Sonatype? I think we might be missing a key.

**Comment by vkostyukov** [comment]
I just re-added the same deploy (public) key. I have no idea why Github decided to remove them but I recall this already happened to me in the other Finagle repos. Can you folks give it a try one more time?

**Comment by rpless** [comment]
Awesome thanks @vkostyukov. I'll re-try the job.

**Comment by vkostyukov** [comment]
It looks like it's gpg keys now:

```
[info] gpg: no default secret key: No secret key
[info] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: Failure running 'gpg --batch --pinentry-mode
```

**Comment by vkostyukov** [comment]
Trying to move gpg keys under gnupg folder here: https://github.com/finagle/finch/pull/1469

**Comment by sergeykolbasov** [comment]
@vkostyukov Did you set the expiration date on the public key by chance? I remember I ran into the same issue without any helpful error message to later find out that the pub key expired a couple of months ago.

**Comment by rpless** [comment]
It looks like that last commit fixed and the artifacts have been published. Great find @vkostyukov.

**Comment by vkostyukov** [comment]
> @vkostyukov Did you set the expiration date on the public key by chance? I remember I ran into the same issue without any helpful error message to later find out that the pub key expired a couple of months ago.

I don't remember, honestly. It was a few years ago but the build/release still chugging so I think we're good?

**Pull request merged**
