### PR TITLE
Scalac flags

### PR DESCRIPTION
**Pull request by rpless**
For #129. Doesn't include `Xlint` and "Xfatal-warnings" for reasons discussed in the issue.

### CODE REVIEW

**Comment by vkostyukov** [comment]
:+1: Thanks Ryan @rpless!

**Comment by vkostyukov** [comment]
Looks like it's failed to compile for Scala 2.10.4. Ryan @rpless could you please take a look?

**Comment by vkostyukov** [comment]
Hm. Interesting. Looks like there no flag `[error] bad option: '-Ywarn-unused-import'` for Scala 2.10.

**Comment by travisbrown** [comment]
You can add the flag conditionally using `CrossVersion.partialVersion` (see e.g. [Finagle's current configuration](https://github.com/twitter/finagle/blob/1e06db17ca2de4b85209dd2fbc18e635815e994b/project/Build.scala#L17) for Jackson versions).

**Comment by rpless** [comment]
Just saw this. It looks like that flag is only available in 2.11. I'll update with @travisbrown's suggestion.

**Comment by travisbrown** [comment]
:+1: from me.

**Comment by vkostyukov** [comment]
:+1: Superb!

**Pull request merged**
