### PR TITLE
Update Jackson to 2.8.5

### PR DESCRIPTION
**Pull request by vkostyukov**
Let's depend on circe-jackson28 and update our own Jackson dependency to be aligned with Finagle 6.40.

### CODE REVIEW

**Comment by travisbrown** [comment]
👍, but is there a reason to choose 2.8.4 over 2.8.5? I'm assuming they're compatible, but circe-jackson28 depends on the newer one, which will evict the older unless users specifically choose it.

**Comment by vkostyukov** [comment]
Finagle depends on 2.8.4 so I assumed we want to use the same version here. I guess they should be compatible so let's make it 2.8.5.

**Comment by vkostyukov** [comment]
So I updated the version but had to change the dependency itself. Turns out, `jackson-module-scala` isn't published for 2.8.5 and we used to depend on that. I don't see a strong reason for doing that since it's clearly user's concern which Jackson module they want to depend on.

Hope that sounds reasonable.

**Comment by spockz** [comment]
On the other hand, it sounds also reasonable to me that a Scala framework would provide support for serialising scala case classes ootb.

**Pull request merged**
