### PR TITLE
Fix #408: exhaustive match in basicAuth

### LINKED ISSUE #408: Fix a bug in basicAuth
@roanta pointed me a bug in `basicAuth` combinator when `MatchError` is thrown at runtime whenever authentifcation is uncucessful.

### PR DESCRIPTION
**Pull request by roanta**
I also moved encoding over to `java.util.Base64` which is now available in Java8.

### CODE REVIEW

**Comment by vkostyukov** [comment]
Thanks Ruben!

We haven't gave up on Java 7 yet: that's why build id failed. Although, I'd been vaguely thinking of dropping Java 7 support, but this unlikely happen before 1.0. Do you mind keep using Util's `Base64StringEncoder` here?

**Comment by roanta** [comment]
Sure, i'll revert to `Base64StringEncoder`.

**Comment by vkostyukov** [comment]
Hey @roanta! Any chance you can rebase this patch and revert to `Base64StringEncoder `? We're pretty close to release. The only thing is left if a traditional doc update PR, which I'm working on right now.

**Comment by roanta** [comment]
Sorry for the delay, rebased and updated.

**Comment by vkostyukov** [comment]
Nice! Thanks @roanta!

**Pull request merged**
