### PR TITLE
Update Cats to 0.9

### PR DESCRIPTION
**Pull request by vkostyukov**
Waiting on
- Circe: https://github.com/circe/circe/pull/548
- Catbird (not in progress)

### CODE REVIEW

**Comment by travisbrown** [comment]
The core circe project's out, but not circe-jackson. I've got to step away from the computer for an hour, but will get it published immediately after that.

**Comment by vkostyukov** [comment]
Thanks @travisbrown! Are there any plans on releasing catbird for Cats 0.9 today as well? Just let me know if there anything I can help with.

**Comment by travisbrown** [comment]
Oh, sorry—catbird's been updated since Sunday night: https://github.com/travisbrown/catbird/releases/tag/v0.11.0

**Comment by travisbrown** [comment]
Okay, circe-jackson is published, so you should be able to update both circe versions and catbird and have everything work!

**Comment by vkostyukov** [comment]
Thanks a lot @travisbrown!

**Pull request merged**
